name: 'Base64 QR Code Generator'
on: 
  pull_request:
    branches:
      - master
jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: fedeorlandau/better-qr-code-generator@master
        id: qrcode
        with:
          content: https://github.com/fedeorlandau
      - run: echo "${{ steps.qrcode.outputs.QR_TEXT }}"
