name: 'Base64 QR Code Generator'
on: [push]
jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: fedeorlandau/better-qr-code-generator@v7
        id: qrcode
        with:
          content: https://github.com/fedeorlandau
      - run: echo ${{ steps.qrcode.outputs.base64 }}
