name: 'Base64 QR Code Generator'
on: 
  pull_request:
    types: [edited]

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: hammadj/qr-code-generator@master
        id: qrcode
        with:
          content: https://github.com/hammadj
      - run: echo ${{ steps.qrcode.output.data }}
